spring:
  application:
    name: grocery-marketplace-product-queryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/grocery-marketplace
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    platform: postgres
    initialization-mode: always
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false

